# Generated by Django 5.2.3 on 2025-06-30 21:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateTimeField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('CEDIS', 'Cedis'), ('DOLLARS', 'Dollars')], default='CEDIS')),
                ('reimbursable', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Trip', 'Trip'), ('Services', 'Services'), ('Catering', 'Catering')], default='Services')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
